---

- name: Install KVM packages
  hosts: lab_main
  remote_user: worker_01

  tasks:
  - name: Install KVM server
    become: true
    community.general.zypper:
      type: pattern  
      name: kvm_server
      state: present

  - name: Install KVM tools
    become: true   
    community.general.zypper:
      type: pattern
      name: kvm_tools
      state: present

  - name: Enable KVM service
    become: true
    ansible.builtin.systemd_service:
      name: libvirtd
      state: started
      enabled: true
